version: '3.1'

services:
    zookeeper:
        container_name: zookeeper-udemy-learn
        image: confluentinc/cp-zookeeper:7.4.1
        ports:
            - '2181:2181'
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    kafka:
        container_name: kafka-udemy-learn
        image: confluentinc/cp-kafka:7.4.1
        ports:
            - '29092:29092'
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CREATE_TOPICS: 'kafk-learn.0:1:1'
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
        depends_on:
            - zookeeper
    kafka-ui:
        container_name: kafka-udemy-ui
        image: provectuslabs/kafka-ui:latest
        ports:
            - 8080:8080
        environment:
            DYNAMIC_CONFIG_ENABLED: true
            KAFKA_CLUSTERS_0_NAME: Udemy
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
            LOGGING_LEVEL_ROOT: error
            LOGGING_LEVEL_COM_PROVECTUS: error
        depends_on:
            - kafka
